import { type BranchList } from './BranchList';
import { type ChangedFile } from './ChangedFile';
import { type ConflictReport } from './ConflictReport';
import { type ConflictFilePreview } from './ConflictFilePreview';
import { type MrDiffPayload } from './MrDiffPayload';
import { type RepoInfo } from './RepoInfo';
import { type ViewMode } from './ViewMode';
import { type GitSyncOperation } from './GitSyncOperation';
import { type GitSyncOptions } from './GitSyncOptions';
import { type FileBlamePayload } from './FileBlamePayload';
import { type SandboxType } from './SandboxType';
import { type SandboxAdapterInfo } from './SandboxAdapterInfo';
import { type SandboxInstanceInfo } from './SandboxInstanceInfo';
import { type SandboxExecutionResult } from './SandboxExecutionResult';

export interface GitState {
  currentRepo: RepoInfo | null;
  recentRepos: RepoInfo[];
  branches: BranchList | null;
  baseBranch: string;
  compareBranch: string;
  diffPayload: MrDiffPayload | null;
  conflictReport: ConflictReport | null;
  diffError: string | null;
  conflictCheckError: string | null;
  selectedFile: ChangedFile | null;
  viewMode: ViewMode;
  fileListLayout: 'flat' | 'tree';
  isInitializing: boolean;
  isLoading: boolean;
  isDiffLoading: boolean;
  isSyncing: boolean;
  syncStatus: string | null;
  error: string | null;

  initApp: (restoreRecent?: boolean) => Promise<void>;
  attachRepoToCurrentWindow: (repo: RepoInfo) => Promise<void>;
  loadRecentRepos: () => Promise<void>;
  openRepoDialog: (forceNewWindow?: boolean) => Promise<void>;
  selectRepo: (repo: RepoInfo) => Promise<void>;
  removeRecentRepo: (id: string) => Promise<void>;
  clearRecentRepos: () => Promise<void>;
  fetchBranches: (repoPath: string) => Promise<void>;
  setBaseBranch: (branch: string) => Promise<void>;
  setCompareBranch: (branch: string) => Promise<void>;
  setBranchComparison: (base: string, compare: string) => Promise<void>;
  swapBranches: () => Promise<void>;
  loadDiff: () => Promise<void>;
  refreshDiff: () => Promise<void>;
  selectFile: (file: ChangedFile | null) => void;
  selectNextFile: () => void;
  selectPrevFile: () => void;
  selectNextConflictFile: () => void;
  selectPrevConflictFile: () => void;
  setViewMode: (mode: ViewMode) => void;
  setFileListLayout: (layout: 'flat' | 'tree') => void;
  remotes: string[];
  remoteUrl: string | null;
  isRebasing: boolean;
  toastMessage: string | null;
  showToast: (msg: string) => void;
  isPullFromOpen: boolean;
  isMergeFromOpen: boolean;
  isRebaseFromOpen: boolean;
  isGitGraphOpen: boolean;
  isRemoteUrlFromOpen: boolean;
  isCloneModalOpen: boolean;
  targetFileForUrl: ChangedFile | null;
  setIsPullFromOpen: (open: boolean) => void;
  setIsMergeFromOpen: (open: boolean) => void;
  setIsRebaseFromOpen: (open: boolean) => void;
  setIsGitGraphOpen: (open: boolean) => void;
  setIsRemoteUrlFromOpen: (open: boolean) => void;
  setIsCloneModalOpen: (open: boolean) => void;
  cloneRepo: (url: string, targetPath: string, credentialId?: string) => Promise<RepoInfo | null>;
  pickCloneFolder: () => Promise<string | null>;
  setTargetFileForUrl: (file: ChangedFile | null) => void;
  fetchRemotes: (repoPath: string) => Promise<void>;
  fetchRemoteUrl: (repoPath: string) => Promise<string | null>;
  checkRebaseStatus: (repoPath?: string) => Promise<boolean>;
  runSync: (op: GitSyncOperation, options?: GitSyncOptions) => Promise<void>;
  fileViewTab: 'diff' | 'blame' | 'conflicts';
  blamePayload: FileBlamePayload | null;
  isBlameLoading: boolean;
  blameError: string | null;
  blameRevision: string;
  blameIgnoreWhitespace: boolean;
  activeConflictPreview: ConflictFilePreview | null;
  isConflictLoading: boolean;
  conflictPreviewError: string | null;
  setFileViewTab: (tab: 'diff' | 'blame' | 'conflicts') => void;
  setBlameRevision: (rev: string) => void;
  setBlameIgnoreWhitespace: (ignore: boolean) => void;
  fetchFileBlame: (filePath?: string, revision?: string, ignoreWhitespace?: boolean) => Promise<void>;
  fetchConflictPreview: (filePath?: string) => Promise<void>;
  toggleFileBlame: () => void;
  activeSandboxType: SandboxType;
  availableSandboxes: SandboxAdapterInfo[];
  activeSandboxInstances: SandboxInstanceInfo[];
  isSandboxLoading: boolean;
  fetchAvailableSandboxes: () => Promise<void>;
  fetchActiveSandbox: () => Promise<void>;
  setActiveSandbox: (type: SandboxType) => Promise<void>;
  createSandboxInstance: () => Promise<SandboxInstanceInfo | null>;
  destroySandboxInstance: (id: string) => Promise<void>;
  executeSandboxCommand: (id: string, command: string, args: string[]) => Promise<SandboxExecutionResult | null>;
  clearError: () => void;
  closeRepo: () => Promise<void>;
}
