// Automatically generated by scripts/generate-about-info.mjs
// Do not edit manually. Run 'npm run dev' or 'npm run build' to regenerate.

export interface SoftwareAboutInfo {
  name: string;
  author: string;
  packageVersion: string;
  gitCommit: string;
  arch: string;
  version: string;
  releaseDate: string;
  currentYear: string;
  copyright: string;
  license: string;
  tagline: string;
  description: string;
  website: string;
  os?: string;
}

export const SOFTWARE_ABOUT: SoftwareAboutInfo = {
  "name": "Stage0",
  "author": "Anh Quoc Tran",
  "packageVersion": "0.1.0",
  "gitCommit": "88a6195",
  "arch": "x64",
  "version": "0.1.0__88a6195_x64",
  "releaseDate": "2026-10-01",
  "currentYear": "2026",
  "copyright": "Copyright @ 2026 Anh Quoc Tran. Licensed under the MIT license.",
  "license": "MIT",
  "tagline": "Local-First Virtual MR / PR Sandbox",
  "description": "Stage0 simulates 3-dot branch comparisons and merge conflict predictions completely in memory via git merge-tree with zero disk modifications.",
  "website": "https://github.com/anhquoctran/stage0",
  "os": "windows"
};
