// Automatically generated by scripts/generate-about-info.mjs
// Do not edit manually. Run 'npm run dev' or 'npm run build' to regenerate.

export interface SoftwareAboutInfo {
  name: string;
  author: string;
  packageVersion: string;
  gitCommit: string;
  arch: string;
  version: string;
  releaseDate: string;
  currentYear: string;
  copyright: string;
  license: string;
  tagline: string;
  description: string;
  website: string;
  os?: string;
}

export const SOFTWARE_ABOUT: SoftwareAboutInfo = {
  "name": "Stage0",
  "author": "Anh Quoc Tran",
  "packageVersion": "0.1.1",
  "gitCommit": "1741ef3",
  "arch": "amd64",
  "version": "0.1.1+1741ef3.windows.amd64",
  "releaseDate": "2026-10-02",
  "currentYear": "2026",
  "copyright": "Copyright @ 2026 Anh Quoc Tran. Licensed under the MIT license.",
  "license": "MIT",
  "tagline": "Local-First Virtual MR / PR Sandbox",
  "description": "Stage0 reviews branch comparisons and predicts merge conflicts without checking out or merging into the user's working tree or index. Git may still write objects to the repository's object database.",
  "website": "https://github.com/anhquoctran/stage0",
  "os": "windows"
};
