; ==============================================================================
; Stage0 NSIS Installer Hooks
; Automatically generated by scripts/generate-about-info.mjs
; Configures Add/Remove Programs (Control Panel) with full metadata
; ==============================================================================

!macro NSIS_HOOK_POSTINSTALL
  ; Set custom DisplayVersion in Windows Registry (Control Panel & Settings > Apps)
  WriteRegStr SHCTX "${UNINSTKEY}" "DisplayName" "Stage0"
  WriteRegStr SHCTX "${UNINSTKEY}" "DisplayVersion" "0.1.2+e3cc2cc.windows.amd64"
  WriteRegStr SHCTX "${UNINSTKEY}" "Publisher" "Anh Quoc Tran"
  WriteRegStr SHCTX "${UNINSTKEY}" "Comments" "Stage0 - Local-First Virtual MR / PR Sandbox. Author: Anh Quoc Tran. Copyright @ 2026 Anh Quoc Tran. Licensed under the MIT license."
  WriteRegStr SHCTX "${UNINSTKEY}" "Contact" "Anh Quoc Tran"
  WriteRegStr SHCTX "${UNINSTKEY}" "HelpLink" "https://github.com/anhquoctran/stage0"
  WriteRegStr SHCTX "${UNINSTKEY}" "URLInfoAbout" "https://github.com/anhquoctran/stage0"
!macroend
