import type { GuardrailPolicy } from './GuardrailPolicy';

export const DEFAULT_GUARDRAIL_POLICY: GuardrailPolicy = {
  mode: 'balanced',
  allowed_commands: [
    'cargo',
    'rustc',
    'npm',
    'npx',
    'pnpm',
    'yarn',
    'node',
    'pytest',
    'python',
    'python3',
    'go',
    'dotnet',
    'make',
    'git',
  ],
  blocked_commands: [
    'rm',
    'del',
    'rmdir',
    'format',
    'mkfs',
    'dd',
    'fdisk',
    'shutdown',
    'reboot',
    'kill',
    'killall',
    'taskkill',
    'curl',
    'wget',
    'powershell',
    'cmd',
  ],
  blocked_patterns: [
    '| sh',
    '| bash',
    '|sh',
    '|bash',
    '> /dev/',
    '>/dev/',
    'sudo ',
    'chmod 777',
    ':(){ :|:& };:',
    '--force',
    '-f',
    'clean -xdf',
    'clean -fdx',
  ],
  sensitive_path_patterns: [
    '.env',
    '.env.',
    '.git/config',
    '.git/credentials',
    'id_rsa',
    'id_ed25519',
    '.pem',
    '.key',
    '.pkcs12',
    '.pfx',
    'token',
    'secret',
    'credentials.json',
    'service-account',
  ],
  max_execution_timeout_secs: 45,
  max_file_read_lines: 2500,
  max_output_bytes: 65536,
  rate_limit_per_minute: 60,
  require_human_confirmation_for_commands: false,
  require_human_confirmation_for_writes: true,
};

export type { GuardrailMode } from './GuardrailMode';
export type { GuardrailSeverity } from './GuardrailSeverity';
export type { GuardrailViolation } from './GuardrailViolation';
export type { GuardrailPolicy } from './GuardrailPolicy';
export type { GuardrailAuditEvent } from './GuardrailAuditEvent';
export type { GuardrailEvaluationResult } from './GuardrailEvaluationResult';
